### ISSUE TITLE
Submenus -- but still radial

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-cxtmenu#12]

**Comment by AjitPS** [comment]
Hi, are there any updates on the development of <b>radial sub-menus</b> feature for the context menus ?

I am currently working with the <b>cxtmenu</b> plugin but it is limited in terms of the no. of menu items and so having radial sub-menus would be very useful. 

Meanwhile, in the existing cxtmenu, is there a way to reduce <b>font-size</b> for the item/ <b>text</b> in order to accommodate a few more options in the menu.

**Comment by AjitPS** [comment]
Also, in the existing <b>cxtmenu</b>, is there a way to add <b>tooltip text</b> to the items as that might allow users to add more menu items with shorter text with its description in the tooltip.

**Comment by Braintelligence** [comment]
:+1:

**Comment by AjitPS** [comment]
Any updates on this ?

**Comment by AjitPS** [comment]
Also, in the existing cxtmenu, is there a way to reduce <b>font-size</b> for the item/ <b>text</b> in order to accommodate a few more options in the menu.

**Comment by maxkfranz** [comment]
The only functional way of doing this that comes to mind is to slice up a command into subcommands.  On hover, a subcommand would enlarge so that it's more readable.

If there's interest in implementing this or similar, feel free to fork and pull request.

**Comment by maxkfranz** [comment]
@AjitPS Use the `cxtmenu-content` class in your CSS.

**Comment by AjitPS** [comment]
Thanks Max. I will look into implementing this feature.

**Comment by cornevin** [comment]
@AjitPS Did you succeed implementing radial sub-menus ? I'm trying to do it too.

**Comment by AjitPS** [comment]
Hi @cornevin , I haven't worked on this feature yet. I'll post on this page when I do get around to implementing this.
Meanwhile, kindly let me know whether you have managed to implement it ? Thanks.

**Comment by jri** [comment]
Just for inspiration how radial submenus might look like:
https://www.youtube.com/watch?v=dVsx4I8gkKk
