### ISSUE TITLE
Demo doesn't seem to be working on nodes

### ISSUE THREAD

**Issue by joshuahhh** [cytoscape/cytoscape.js-cxtmenu#37]
I have cloned the repo (v2.6.1) and am testing the demo file in Chrome and Firefox on Mac. I see strange results:

- Menus defined on "core" are working fine: Hold the mouse down over the background, and a menu will pop up. Move the mouse over a menu item and release, and the appropriate message is logged to the console.

- Menus defined on nodes are not working: Hold the mouse down over a node, and a menu will pop up. Move the mouse over a menu item and release, and nothing will be logged to the console. However, if, after doing this, you drag the node from one point to another, the message from the menu selection will be logged to the console when you release the mouse button.

Reading the code, this behavior makes sense to me: the command's `select` property is called from a `'cxttapend tapend'` event handler which is attached to the node selector... but `tapend` will only be triggered on a node if the mouse is released while over the node, right? So releasing the mouse over the menu, away from the node, will not trigger `tapend`?

Am I missing something here? (Thanks!)

**Comment by maxkfranz** [comment]
@joshuahhh 

Thanks for the information (and the PR!), but I can't reproduce what you describe.  I tried the demo on both Chrome and Firefox, and I get the expected behaviour.

The selector on that event listener definitely needs to be there, else support for multiple instances/calls would be broken for different selectors:  You could trigger menus on nonmatching elements.

**Comment by maxkfranz** [comment]
@joshuahhh Are you running any browser extensions that could be causing issues?

**Comment by maxkfranz** [comment]
Not reproducible and no response from OP; closing
