### ISSUE TITLE
Right click does not activate selection

### ISSUE THREAD

**Issue by geirmeyer** [cytoscape/cytoscape.js-cxtmenu#53]
Right-click selection only selects, but does not activate the command.

This can be reproduced using demo.html in version 2.9.4.

To provoke issue:
1) Right-Click on a node so that the menu shows
2) Select a command
3) Release the right-click. Command is not executed, and no console.log output is shown in the debug window.

When clicking on a node, and holding it down, the menu will be shown due to 'taphold'. Select a command and the command is activated and the output is shown.

**Comment by maxkfranz** [comment]
@lukejpreston I think your PR #51 interferes with the cxt usecase.  Would you please take a look to see where your change is conflicting?  Thanks

**Comment by lukejpreston** [comment]
It seems to be a similar bug to the one I fixed
@geirmeyer could you confirm that it works for left click? i.e.

1. Left-Click on a node so that the menu shows
2. Select a command
3. Release the left-click

From what I can observe, it is a similar but to the one I fixed.
If you use the right-click it opens the menu, it does select the option. But the option will not run until you interact with a node or an edge e.g. click on any node.

I do not know cytoscapes events for right click e.g. `cy.on('righttap')` isn't a thing. So let me know how to do that and this can be fixed super quick 😸

**Comment by maxkfranz** [comment]
It's supposed to work with swipes of cxt events, not taps: http://js.cytoscape.org/#events/user-input-device-events

**Comment by geirmeyer** [comment]
@lukejpreston left click works.
More details:
1a) Right-click on a node, menu appears, select option, no command is executed
1b) Click on any node, the command selected in right-click step above is executed.
1c) Instead of clicking on a node as in 1), clicking on edge or core does not execute command

Version 2.9.3: 
Same as 2.9.4.

Versions 2.9.2, and 2.9.0:
Right-click works as expected, command is executed.
Left-click, hold a bit, menu appears, option is selected, no command is executed
2.9.0 and 2.9.2 works opposite to 2.9.4.

Version 2.9.1:
 Does not work, no menu what so ever?

**Comment by maxkfranz** [comment]
2.9.3 and 2.9.4 are both the same (with @lukejpreston's PR), but 2.9.4 just removes some linting warnings.

**Comment by maxkfranz** [comment]
I've reverted #52 

2.9.5 should work OK
