### ISSUE TITLE
Touch selection is not working

### ISSUE THREAD

**Issue by CMaylone** [cytoscape/cytoscape.js-cxtmenu#54]
### Steps to reproduce
* Using a touch device or chrome debugger
* tap and hold to bring up menu
* release to select but it does not select

This works in `2.9.2` but not in `2.9.4`. This behavior occurred in the chrome debugger with touch events and on my Android phone.

**Comment by maxkfranz** [comment]
This is because of PR https://github.com/cytoscape/cytoscape.js-cxtmenu/pull/52

See also https://github.com/cytoscape/cytoscape.js-cxtmenu/issues/53

I've rolled back #52 and put new commits for fixes that followed thereafter.  2.9.5 should work like 2.9.2 for cxt swipes, and it should work like 2.9.4 for taphold swipes.
