### ISSUE TITLE
`commands` function returning a promise

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js-cxtmenu#67]
A function passed to the `commands` option should be able to return a promise. The menu would appear once the promise is resolved. Currently (3.0) this is not supported.

My application needs to dynamically enable/disable certain commands based on the user's permission. The permission calculation involves asynchronism.

**Comment by jri** [comment]
@maxkfranz What do you think about the `commands` function returning a promise?

Alternative: manipulate the commands dynamically while the menu is open, e.g. disabling a command.

**Comment by maxkfranz** [comment]
Personally, I don't think it would work well unless you show the intermediate loading state somehow.  Waiting for a potentially long async op to complete to show anything, like the menu, could give bad ux.  

Your idea could be implemented by adding `menu.disable()`, `menu.enable()`, and `menu.updateCommands()` etc. to the returned `menu` object -- rather than introducing async directly to the extension.  

Anyway, it's an interesting idea but it's not something that I have time to implement myself any time soon.

**Comment by jri** [comment]
I plan to provide a pull request realizing the promise approach very soon. It will be fully compatible with current API and will have no performance impact.

Async does not necessarily imply a long operation (no server request might be involved at all) and bad ux. The app developer is still free to provide a load indicator if due.

From my perspective the other approach -- extending the API -- would be both harder to implement in the extension, and harder to use by the app developer (as she must relate the async response to an open menu somehow).
