### ISSUE TITLE
command's `enabled` and `content` as a function of `ele`

### ISSUE THREAD

**Issue by vict0rsch** [cytoscape/cytoscape.js-cxtmenu#71]
It would be nice if commands' existence and content could depend on the element you click, which would mean implementing the command's `enabled` and `content`  attributes as functions of the element clicked.

Cheers for the good work!

PS: This could ideally also be the case for other menu parameters like `activeFillColor` or `itemColor`

**Comment by Secretmapper** [comment]
We can go even further and make commands itself be dependent on content

**Comment by thehappydinoa** [comment]
Hi there, this is something I am interested in as well. Might there be any way we could reopen this feature request?

**Comment by Callmoon** [comment]
Hey everyone,

if you have a look onto the example configuration there is a comment with:
`// function( ele ){ return [ /*...*/ ] }, // a function that returns commands or a promise of commands`

That means instead of return a static Array of commands you can also return them dynamically as a function with the selected element parameter.
```
 commands: (ele: Collection) => {
      return [
     //command objects,
     ]
}
```

That means you can control the `enabled` attribute  very easily like this:

```
{
  content: 'Only enabled if less than two connections',
  select: (ele: Collection) => {
  console.log('selection possible because command is enabled')
  },
  enabled: ele.nodes().connectedEdges().length < 2  //here we can access the element from where the context menu was triggered
},
```

That means also you can control the visibility of the commands through filtering before returning the array.
For example by the previously setted `enabled `attribute:

```
 commands: (ele: Collection) => {
      return [
     //command objects,
     ].filter(command => command.enabled)
}
```
