### ISSUE TITLE
Cancel when mouse pointer is outside menu

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js-cxtmenu#81]
It happens repeatedly that users of my application choose a command from the menu when they actually want *cancel* the menu. From using other menus they expect releasing the mouse button *outside the menu* would cancel it. In contrast the Cytoscape menu still selects a command even if the mouse pointer is outside the menu.

Current behavior:
- The blue highlight remains even if the mouse pointer is outside the menu (see screenshot)

Expected behavior:
- The blue highlight disappears as soon as the mouse pointer is outside the menu (that is the mouse distance is `> menuRadius + activePadding`). Releasing the mouse button does *not* select any command and closes the menu.

![image](https://user-images.githubusercontent.com/120337/63309846-7c06a900-c2f8-11e9-8690-123b91905101.png)

**Comment by maxkfranz** [comment]
Frankly, the design of other menus -- to cancel when outside of the circle itself -- is not so good.  Each slice is much easier to select when the area is infinite (by Fitts' Law), like in this cxtmenu library.  Infinite area also enables users to make quick swipe gestures.

The centre is a deadzone, but it's a small area.  You can also make the one of the slices a deadzone for cancellation.  The star icon in the image is an example of that.  Visually, you can make it clearer that it's a deadzone by making the background of the slice transparent.  If you want to make it completely explicit, you could put the word "cancel" on the deadzone slice.

**Comment by maxkfranz** [comment]
Example:

![Untitled 2](https://user-images.githubusercontent.com/989043/63351385-20a2de00-c32d-11e9-8afd-62f6b4d4c565.png)

For this usecase, it would be useful to be able to centre the first entry at the top of the circle.  That would be the best place to put the deadzone slice.

**Comment by jri** [comment]
I understand your concept of a deadzone slice, thank you for that!, but it would not solve the situation described.

Problem is users are using menus for decades and have internalized expectations. Fact is a lot of my application's users complain repeatedly about the bad user experience with cxtmenu as they regularly select a command when they actually want cancel. This habit is deeply internalized, and I accept that re-educating my users is not an option.

My users are desktop users, not touch users.

Apparently my proposal has no priority for you, and this is not a problem. I'm sure you have lot of work on your table.

Would you accept a pull request (and release a new version) that realizes this concept:
- Introduce another config option `outsideMenuCancel`, boolean:
    - `false` (default): current behavior
    - `true`: the blue highlight disappears as soon as the mouse pointer is outside the menu (that is distance is `> menuRadius + activePadding`). Releasing the mouse button there does not select any command and closes the menu.

Presumably this is easy to implement, and will not introduce any incompatibilities or complications.

**Comment by maxkfranz** [comment]
> My users are desktop users, not touch users.

The concept of a swipe gesture also works with a mouse.  It's more forgiving to be able to have a larger area in which to drag the mouse for a menu selection.

> Problem is users are using menus for decades and have internalized expectations. Fact is a lot of my application's users complain repeatedly about the bad user experience with cxtmenu as they regularly select a command when they actually want cancel. This habit is deeply internalized, and I accept that re-educating my users is not an option.

Most users have little or no experience with radial menus, so some learning is necessary for most users in any case.  I think the source of the issue is that by default there is no visually obvious cancellation area.  The centre of the menu is a cancellation area, but it's small and not obvious.  The deadzone slice addresses this concern, since it's an obviously cut-out area in the menu.

If you really want to cancel outside of the menu circle, I'm frankly not enthusiastic about it.  That being said, I understand your concerns and I don't think that an option should be forbidden outright.  I would be more inclined to have an option that specifies an integer value for the cancellation radius rather than a boolean.  

That allows for having a radius that's larger than the visible circle, which makes it easier to select menu items.  That cancellation radius could, for example, be set to the same radius as the blue active slice indicator to give a visual indication to users of how the regions are delineated.  Alternatively, the blue slice indicator could shrink in size as you get closer to the cancellation radius to provide visual feedback.  Or if you're so inclined, you could make the cancellation radius equal to the radius of the visible black circle.  The main thing is that the user is given generous hit areas, visual signifiers, and visual feedback that correspond to the available actions.

With an integer value, the API of the extension does not suggest -- or force -- a consumer to use the equal radius case.  While I'm not against allowing that case, I don't want to encourage it.

I think if you tested the deadzone slice with users, you might be surprised with the results.  If not or if you don't prefer, you're free to make a PR for the customisable cancellation radius.

**Comment by nkobby** [comment]
@maxkfranz and @jri, any conclusion to this issue? I have a similar problem so the pull request for `outsideMenuCancel` config option will be very useful. If no one is working on it I can implement it.

**Comment by jri** [comment]
@nkobby from my perspective it would be great if you implement it. (I can't do it at the moment.) Thank you very much for chiming in!

**Comment by jri** [comment]
@nkobby do you need any support to work on this?

**Comment by andres-k** [comment]
Is this still on anyones roadmap or as it's marked stale, everybody lost interest?

**Comment by jri** [comment]
I still have high demand for this improvement, but can't implement it at the moment.

**Comment by HEmile** [comment]
Hi there, I've implemented this request in this branch: https://github.com/cytoscape/cytoscape.js-cxtmenu/pull/114

**Comment by jri** [comment]
@HEmile that's great! Thank you very much!
@maxkfranz do you think you can merge?

**Comment by maxkfranz** [comment]
@HEmile's PR has been released as v3.4.0

**Comment by jri** [comment]
@HEmile Canceling works perfect! 3.4.0 is great! 😄
