### ISSUE TITLE
event/function to get the position of the cxtmenu on the cytoscape graph?

### ISSUE THREAD

**Issue by aoighost** [cytoscape/cytoscape.js-cxtmenu#85]
Is there a way to get the position x/y of the cxtmenu on the cytoscape graph and use it to pass to a variable in a menu item?

**Comment by aoighost** [comment]
Basically what I'm trying to do is create a cxtmenu that when you right click on a part of the canvas, it pops up the cxtmenu and has an option to create a node on the graph at that position

**Comment by maxkfranz** [comment]
I find it's better to track the last mousemove position and use that.  You've swiped away from the menu's centre point once you've finished swiping a menu item slice.  It's better to have the new node right under where the cursor is at the end of the gesture.  Otherwise, you have to move the cursor back and forth to get at the new node.

**Comment by aoighost** [comment]
A. that doesn't answer my question.

B. that's goddamn horrible UX, that sounds unintuitive as fuck.

C. Even if it wasn't, I'm popping up a form on button press to create the node and the contents of the node, again, antidesign.
